//! tar.gz snapshot backend (Phase 6.3).
//!
//! Layout: `<mount>/.anolisa/snapshots/<id>.tar.gz`, with a parallel
//! `<id>.json` sidecar holding metadata (name, created_at, ...).
//!
//! - Create: walks the mount root EXCLUDING `.anolisa/`, writes a gzipped
//!   tarball, then atomically renames into place.
//! - List: scans the snapshots dir for sidecars and returns them oldest →
//!   newest.
//! - Restore: extracts into a sibling staging dir, then atomically swaps
//!   the user-visible content (everything except `.anolisa/`) so a crash
//!   mid-restore can never leave a half-extracted tree.

use std::fs::{File, OpenOptions};
use std::io::Write;
use std::os::fd::AsFd;
use std::path::Path;
use std::sync::Mutex;

use chrono::Utc;
use flate2::Compression;
use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use walkdir::WalkDir;

use super::{SNAPSHOTS_DIR, SnapshotInfo, snapshots_dir};
use crate::error::{MemoryError, Result};
use crate::ns::MountPoint;

const BACKEND_TAG: &str = "tar.gz";

/// Process-wide write mutex serializing concurrent `restore_tarball`
/// invocations. Restore is destructive (renames every top-level entry,
/// moves staging in) — without this lock, two concurrent restores would
/// race on the rename-aside step and leave the mount in a half-swapped
/// state. The mutex is held for the full restore so concurrent file
/// tools see either the pre- or post-restore state, never an interleave.
static RESTORE_LOCK: Mutex<()> = Mutex::new(());

/// Reject snapshot ids that could escape `<mount>/.anolisa/snapshots/`.
/// `id` is interpolated into `<id>.tar.gz` and `.<id>.staging` paths
/// without further canonicalisation; a value like `../../../tmp/evil`
/// would let `archive_path` and `staging` resolve outside the snapshot
/// directory, and the subsequent `remove_dir_all(&staging)` would then
/// destroy arbitrary directories the caller can write to.
///
/// Accept only the alphabet generated by `new_snapshot_id` plus a small
/// human-friendly extension (letters / digits / `_` / `-` / `.`), up to
/// 128 bytes total. Anything else — slashes, NUL, `..`, control
/// characters — is refused.
pub(crate) fn validate_snapshot_id(id: &str) -> Result<()> {
    if id.is_empty() {
        return Err(MemoryError::InvalidArgument(
            "snapshot id must not be empty".into(),
        ));
    }
    if id.len() > 128 {
        return Err(MemoryError::InvalidArgument(format!(
            "snapshot id length {} exceeds 128 bytes",
            id.len()
        )));
    }
    if id.contains("..") {
        return Err(MemoryError::InvalidArgument(format!(
            "snapshot id '{id}' contains '..'"
        )));
    }
    for ch in id.chars() {
        let ok = ch.is_ascii_alphanumeric() || matches!(ch, '_' | '-' | '.');
        if !ok {
            return Err(MemoryError::InvalidArgument(format!(
                "snapshot id '{id}' contains forbidden character {ch:?}"
            )));
        }
    }
    Ok(())
}

pub fn create_tarball(mount: &MountPoint, id: &str, name: &str) -> Result<SnapshotInfo> {
    validate_snapshot_id(id)?;
    let dir = snapshots_dir(mount);
    std::fs::create_dir_all(&dir)?;

    let archive_path = dir.join(format!("{id}.tar.gz"));
    let tmp_path = dir.join(format!("{id}.tar.gz.partial"));

    // 1. Stream mount tree → tmp tarball, skipping .anolisa/.
    {
        let f = File::create(&tmp_path)?;
        let gz = GzEncoder::new(f, Compression::default());
        let mut tar = ::tar::Builder::new(gz);
        // SECURITY: tar::Builder::follow_symlinks defaults to true, which
        // would silently inline a symlink target's content into the
        // archive — e.g. a `notes/leak -> /etc/passwd` link inside the
        // mount would leak `/etc/passwd` into the snapshot, and on
        // restore that content lands at `notes/leak` as a regular file.
        // Disable that, then refuse symlink entries explicitly so the
        // mount invariant ("no symlinks ever") is enforced at create.
        tar.follow_symlinks(false);

        let meta_dir = mount.meta_dir.clone();
        for entry in WalkDir::new(&mount.root)
            .min_depth(1)
            .follow_links(false)
            .into_iter()
            .filter_entry(|e| !e.path().starts_with(&meta_dir))
        {
            let entry = entry.map_err(|e| MemoryError::Other(format!("walk: {e}")))?;
            let path = entry.path();
            let rel = path
                .strip_prefix(&mount.root)
                .map_err(|e| MemoryError::Other(format!("strip: {e}")))?;
            // walkdir + follow_links(false) reports lstat-equivalent file
            // type, so any symlink under the mount is corruption or
            // attack — fail loudly rather than serializing it.
            if entry.file_type().is_symlink() {
                return Err(MemoryError::PathOutsideMount(rel.display().to_string()));
            }
            // tar requires non-absolute relative paths; rel is by construction.
            tar.append_path_with_name(path, rel)
                .map_err(|e| MemoryError::Other(format!("tar append {}: {e}", rel.display())))?;
        }
        tar.finish()
            .map_err(|e| MemoryError::Other(format!("tar finish: {e}")))?;
        // GzEncoder::finish runs in Drop; explicit shutdown via `into_inner`
        // not necessary because Builder::finish already flushed payload.
    }

    let size = std::fs::metadata(&tmp_path)?.len();
    // 2. Crash-safe atomic rename: sync the tmp file first so the
    //    inode data is on disk before the rename updates the dirent.
    //    Then sync the parent directory so the dirent is durable.
    let tmp_file = File::open(&tmp_path)?;
    tmp_file.sync_all()?;
    std::fs::rename(&tmp_path, &archive_path)?;
    let dir_fd = File::open(&dir)?;
    dir_fd.sync_all()?;

    // 3. Write sidecar JSON metadata.
    let info = SnapshotInfo {
        id: id.to_string(),
        name: name.to_string(),
        created_at: Utc::now().to_rfc3339(),
        size,
        backend: BACKEND_TAG.into(),
    };
    write_sidecar(&dir.join(format!("{id}.json")), &info)?;
    Ok(info)
}

pub fn list_tarballs(mount: &MountPoint) -> Result<Vec<SnapshotInfo>> {
    let dir = snapshots_dir(mount);
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }
        if let Ok(info) = read_sidecar(&path) {
            out.push(info);
        }
    }
    out.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    Ok(out)
}

pub fn restore_tarball(mount: &MountPoint, id: &str) -> Result<()> {
    // SECURITY: reject any id that could traverse out of the snapshot dir.
    // Without this, `id="../../tmp/x"` would let `staging` and `archive_path`
    // resolve outside `<mount>/.anolisa/snapshots/`, and the subsequent
    // `remove_dir_all(&staging)` would destroy arbitrary directories.
    validate_snapshot_id(id)?;

    // Serialize concurrent restores: the rename-aside step is not idempotent
    // and two callers swapping at once would interleave rollback entries.
    let _restore_guard = RESTORE_LOCK.lock().unwrap_or_else(|p| p.into_inner());

    let dir = snapshots_dir(mount);
    let archive_path = dir.join(format!("{id}.tar.gz"));
    if !archive_path.exists() {
        return Err(MemoryError::NotFound(format!("snapshot {id}")));
    }

    // 1. Extract under .anolisa/snapshots/.<id>.staging/ — hidden so it
    //    won't show up in `mem_list` if anyone walks the tree.
    let staging_rel_str = format!("{}/{}/.{id}.staging", mount.meta_dir_name(), SNAPSHOTS_DIR);
    let staging_rel = Path::new(&staging_rel_str);
    let staging = mount.root.join(staging_rel);
    if staging.exists() {
        crate::safe_fs::remove_dir_all_safe(mount.root_fd.as_fd(), staging_rel, &staging)?;
    }
    std::fs::create_dir_all(&staging)?;
    {
        let f = File::open(&archive_path)?;
        let gz = GzDecoder::new(f);
        let mut tar = ::tar::Archive::new(gz);
        tar.set_overwrite(false);
        // SECURITY: only allow Regular and Directory entries. Reject
        // Symlink / Hardlink / Device / Fifo — a malicious tarball
        // with a symlink entry would let the unpack write through the
        // link to an arbitrary destination, or leave a dangling symlink
        // inside staging that gets renamed into the mount (step 2b).
        //
        // Directories are created via create_dir_all (idempotent, no
        // overwrite concern). Regular files use unpack_in with
        // overwrite=false so any collision in the freshly-created
        // staging dir is caught as an anomaly.
        for entry in tar
            .entries()
            .map_err(|e| MemoryError::Other(format!("tar entries: {e}")))?
        {
            let mut entry =
                entry.map_err(|e| MemoryError::Other(format!("tar entry read: {e}")))?;
            match entry.header().entry_type() {
                ::tar::EntryType::Regular | ::tar::EntryType::Directory => {
                    // unpack_in validates the entry path stays inside
                    // staging (validate_inside_dst rejects ".." and
                    // absolute paths). This is the same guard that the
                    // old tar.unpack() used; Directory and Regular share
                    // one branch because both go through the same
                    // validation before filesystem dispatch.
                    entry.unpack_in(&staging).map_err(|e| {
                        MemoryError::Other(format!(
                            "tar unpack {}: {e}",
                            entry.path().unwrap_or_default().display()
                        ))
                    })?;
                }
                other => {
                    return Err(MemoryError::InvalidArgument(format!(
                        "snapshot contains forbidden entry type '{}' at {}",
                        entry_type_name(other),
                        entry.path().unwrap_or_default().display()
                    )));
                }
            }
        }
    }

    // 2. Two-stage rename swap. The previous implementation deleted the
    //    entire user-visible tree first, then moved staging in — a crash
    //    in that window left the mount empty. Now we rename each
    //    top-level entry aside with a hidden rollback prefix, move
    //    staging entries in, then drop the rollbacks. On any error we
    //    rename the rollbacks back, leaving the pre-restore state intact.
    //
    //    Renames within the same directory are atomic per POSIX, so each
    //    path at any instant resolves to either its old or new content
    //    (the swap window is bounded by a single rename(2) call, not by
    //    arbitrary IO duration).
    let rollback_prefix = format!(".{id}.rollback.");
    let mut rollbacks: Vec<(std::path::PathBuf, std::path::PathBuf)> = Vec::new();
    let mut applied: Vec<(std::path::PathBuf, std::path::PathBuf)> = Vec::new();

    let restore_result: Result<()> = (|| {
        // 2a. Move every non-meta top-level entry aside.
        for entry in std::fs::read_dir(&mount.root)? {
            let entry = entry?;
            let name = entry.file_name();
            if name == mount.meta_dir_name() {
                continue;
            }
            // Skip any leftover rollback / staging artefacts from a crashed
            // prior restore (defense-in-depth — meta dir owner cleans these).
            if name.to_string_lossy().starts_with(&rollback_prefix) {
                continue;
            }
            let original = entry.path();
            let rolled = mount
                .meta_dir
                .join(format!("{rollback_prefix}{}", name.to_string_lossy()));
            std::fs::rename(&original, &rolled)?;
            rollbacks.push((original, rolled));
        }

        // 2b. Move staging entries into the mount root.
        for entry in std::fs::read_dir(&staging)? {
            let entry = entry?;
            let from = entry.path();
            let to = mount.root.join(entry.file_name());
            std::fs::rename(&from, &to)?;
            applied.push((from, to));
        }
        Ok(())
    })();

    if let Err(e) = restore_result {
        // Rollback: undo any applied staging moves, then move rollbacks back.
        for (from, to) in applied.into_iter().rev() {
            let _ = std::fs::rename(&to, &from);
        }
        for (original, rolled) in rollbacks.into_iter().rev() {
            let _ = std::fs::rename(&rolled, &original);
        }
        let _ = crate::safe_fs::remove_dir_all_safe(mount.root_fd.as_fd(), staging_rel, &staging);
        return Err(e);
    }

    // Invariant: no symlink should exist inside the mount at any time.
    // The entry type filter in step 1 (only Regular + Directory) is the
    // guard that prevents snapshot restore from introducing symlinks;
    // git checkout also filters at its own entry point (see M2 symlink
    // filemode check in git_repo/mod.rs). Anyone adding a new entry type
    // here must ensure it cannot plant symlinks or other escape vectors.

    // 3. Move rollbacks into a recoverable trash dir instead of deleting.
    // The previous implementation `remove_dir_all`-ed every rollback as soon
    // as the swap succeeded — an unrecoverable destruction of the prior
    // state. Operators (or a future GC tool) can purge `.anolisa/trash/`
    // explicitly when they decide the restore is good.
    let trash_dir = mount
        .meta_dir
        .join("trash")
        .join(format!("{}-{id}", Utc::now().format("%Y%m%dT%H%M%SZ")));
    if let Err(e) = std::fs::create_dir_all(&trash_dir) {
        // Trash creation failed — fall back to leaving rollback entries in
        // place so the user still has a recovery path. Log loudly.
        tracing::warn!(
            "could not create trash dir {} ({e}); rollback entries left in meta dir",
            trash_dir.display()
        );
    } else {
        for (original, rolled) in rollbacks {
            let leaf = original
                .file_name()
                .map(|s| s.to_os_string())
                .unwrap_or_else(|| std::ffi::OsString::from("entry"));
            let dest = trash_dir.join(&leaf);
            if let Err(e) = std::fs::rename(&rolled, &dest) {
                tracing::warn!(
                    "could not move rollback {} → {}: {e}",
                    rolled.display(),
                    dest.display()
                );
            }
        }
    }
    if let Err(e) =
        crate::safe_fs::remove_dir_all_safe(mount.root_fd.as_fd(), staging_rel, &staging)
    {
        tracing::warn!("staging cleanup {}: {e}", staging.display());
    }
    Ok(())
}

fn write_sidecar(path: &Path, info: &SnapshotInfo) -> Result<()> {
    let body = serde_json::to_string_pretty(info)?;
    let mut f = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .open(path)?;
    f.write_all(body.as_bytes())?;
    f.sync_all()?;
    Ok(())
}

/// Stable string representation of a tar entry type — avoids Debug
/// formatting whose output may change across tar crate versions.
fn entry_type_name(ty: ::tar::EntryType) -> &'static str {
    match ty {
        ::tar::EntryType::Regular => "Regular",
        ::tar::EntryType::Directory => "Directory",
        ::tar::EntryType::Symlink => "Symlink",
        ::tar::EntryType::Link => "Hardlink",
        ::tar::EntryType::Char => "CharDevice",
        ::tar::EntryType::Block => "BlockDevice",
        ::tar::EntryType::Fifo => "Fifo",
        ::tar::EntryType::Continuous => "Continuous",
        ::tar::EntryType::XHeader => "PAXHeader",
        ::tar::EntryType::XGlobalHeader => "PAXGlobalHeader",
        ::tar::EntryType::GNULongName => "GNULongName",
        ::tar::EntryType::GNULongLink => "GNULongLink",
        ::tar::EntryType::GNUSparse => "GNUSparse",
        _ => "Unknown",
    }
}

fn read_sidecar(path: &Path) -> Result<SnapshotInfo> {
    let body = std::fs::read_to_string(path)?;
    Ok(serde_json::from_str(&body)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_snapshot_id_accepts_generated_form() {
        // The runtime form `snap_<ULID>` and the human form `my.label-1` both pass.
        assert!(validate_snapshot_id("snap_01H8XX0YXM7TQNN8YXMZ7M6FXM").is_ok());
        assert!(validate_snapshot_id("my.label-1").is_ok());
        assert!(validate_snapshot_id("v2025-05-25").is_ok());
    }

    #[test]
    fn validate_snapshot_id_rejects_traversal() {
        // These are the shapes that would let `archive_path` /  `staging`
        // escape `<mount>/.anolisa/snapshots/`.
        assert!(validate_snapshot_id("").is_err());
        assert!(validate_snapshot_id("../escape").is_err());
        assert!(validate_snapshot_id("a/b").is_err());
        assert!(validate_snapshot_id("a\\b").is_err());
        assert!(validate_snapshot_id("a..b").is_err());
        assert!(validate_snapshot_id("a\0b").is_err());
        assert!(validate_snapshot_id("a\nb").is_err());
        assert!(validate_snapshot_id("/abs").is_err());
        // 128-byte limit is enforced.
        assert!(validate_snapshot_id(&"a".repeat(129)).is_err());
    }
}
